import { TPalette } from '../../types';

export const getDarkThemeBackground = (palette: TPalette) => ({
  primary: palette['gray-dark-mode'][950],
  'primary-alt': palette['gray-dark-mode'][900],
  'primary-hover': palette['gray-dark-mode'][800],
  'primary-solid': palette['gray-dark-mode'][900],
  secondary: palette['gray-dark-mode'][900],
  'secondary-alt': palette['gray-dark-mode'][950],
  'secondary-hover': palette['gray-dark-mode'][800],
  'secondary-subtle': palette['gray-dark-mode'][900],
  'secondary-solid': palette['gray-dark-mode'][600],
  tertiary: palette['gray-dark-mode'][800],
  quaternary: palette['gray-dark-mode'][700],
  active: palette['gray-dark-mode'][800],
  disabled: palette['gray-dark-mode'][800],
  'disabled-subtle': palette['gray-dark-mode'][900],
  overlay: palette['gray-dark-mode'][800],
  'brand-primary': palette.brand[500],
  'brand-primary-alt': palette['gray-dark-mode'][800],
  'brand-secondary': palette.brand[600],
  'brand-solid': palette.brand[600],
  'brand-solid-hover': palette.brand[500],
  'brand-section': palette['gray-dark-mode'][800],
  'brand-section-subtle': palette['gray-dark-mode'][950],
  'error-primary': palette.error[500],
  'error-secondary': palette.error[600],
  'error-solid': palette.error[600],
  'warning-primary': palette.warning[500],
  'warning-secondary': palette.warning[600],
  'warning-solid': palette.warning[600],
  'success-primary': palette.success[500],
  'success-secondary': palette.success[600],
  'success-solid': palette.success[600],
});
