import { TPalette } from '../../types';

export const getLightThemeBackground = (palette: TPalette) => ({
  primary: palette.base.white,
  'primary-alt': palette.base.white,
  'primary-hover': palette['gray-light-mode'][50],
  'primary-solid': palette['gray-light-mode'][950],
  secondary: palette['gray-light-mode'][50],
  'secondary-alt': palette['gray-light-mode'][50],
  'secondary-hover': palette['gray-light-mode'][100],
  'secondary-subtle': palette['gray-light-mode'][25],
  'secondary-solid': palette['gray-light-mode'][600],
  tertiary: palette['gray-light-mode'][100],
  quaternary: palette['gray-light-mode'][200],
  active: palette['gray-light-mode'][50],
  disabled: palette['gray-light-mode'][100],
  'disabled-subtle': palette['gray-light-mode'][50],
  overlay: palette['gray-light-mode'][950],
  'brand-primary': palette.brand[50],
  'brand-primary-alt': palette.brand[50],
  'brand-secondary': palette.brand[100],
  'brand-solid': palette.brand[600],
  'brand-solid-hover': palette.brand[700],
  'brand-section': palette.brand[800],
  'brand-section-subtle': palette.brand[700],
  'error-primary': palette.error[50],
  'error-secondary': palette.error[100],
  'error-solid': palette.error[600],
  'warning-primary': palette.warning[50],
  'warning-secondary': palette.warning[100],
  'warning-solid': palette.warning[600],
  'success-primary': palette.success[50],
  'success-secondary': palette.success[100],
  'success-solid': palette.success[600],
});
